<a href="https://colab.research.google.com/github/epythonlab2/AI_4_health/blob/main/module_3_2_financial_data_science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<header style="font-family: 'Inter', sans-serif; background: #ffffff; padding: 16px; border-radius: 8px; border: 1px solid #e1e4e8; display: flex; align-items: center; gap: 12px; box-shadow: 0 2px 8px rgba(0,0,0,0.05); margin-bottom: 10px;">
    <div style="width: 4px; height: 35px; background: linear-gradient(to bottom, #4e73df, #1cc88a); border-radius: 2px;"></div>
    <h1 style="color: #1a1a1a; margin: 0; font-size: 20px; font-weight: 700; border: none;">Module 3: Applications in Healthcare & Finance</h1>
</header>

<div style="font-family: 'Inter', sans-serif; max-width: 900px; margin: 15px 0; padding: 20px; border-radius: 10px; background: #f1f4ff; border: 1px solid #dbe3ff; display: flex; align-items: center; justify-content: space-between; gap: 15px;">
    <div style="flex: 1;">
        <h2 style="margin: 0; color: #2e59d9; font-size: 18px; font-weight: 700; border: none;">Chapter 2: Financial Data Science</h2>
        <span style="display: inline-block; margin-top: 8px; background: #ffffff; padding: 4px 12px; border-radius: 6px; color: #4e73df; font-weight: 800; font-size: 11px; border: 1px solid #dbe3ff; text-transform: uppercase;">12 Hours</span>
    </div>

   <a href="https://linkedin.com/in/dejenet" target="_blank" style="background-color: #0077b5; color: white; padding: 10px 20px; border-radius: 8px; text-decoration: none; font-size: 14px; font-weight: 700; white-space: nowrap;">
        Connect on LinkedIn
    </a>
</div>

###**2. What Is Financial Data Science?**

**Financial data science** applies **statistics**, **machine learning**, and **domain knowledge** to financial data in order to:

- Predict risk

- Detect fraud

- Forecast prices or defaults

- Support business and policy decisions

Unlike many ML domains, mistakes are **costly** here. Models must be accurate, explainable, and stable over time.

####**2.1 Core Financial Datasets**
**1. Stock Market Data**

Stock market data is time-based, fast-moving, volatile, and often unpredictable. It captures how asset prices change over time and reacts quickly to both market behavior and external signals.


**Typical features**

- Date / timestamp

- Open, High, Low, Close (OHLC) prices

- Volume

- Adjusted close

- Corporate actions (splits, dividends)

**Key characteristics**

- **Sequential (order matters):** the order of data points matters. Yesterday always affects today.

- Non-stationary (statistics change over time): averages, variance, and trends shift over time.

- Influenced by external events (news, interest rates): news, macroeconomic indicators, interest rates, and global events can cause sudden changes.

**Common tasks**

- Price forecasting: predicting future prices or returns.

- Volatility estimation: measuring how much prices fluctuate.

- Trend detection: identifying upward, downward, or sideways movements.

- Risk measurement: calculating metrics like drawdown, Value at Risk (VaR), or Sharpe ratio.

**Example: Load stock market data using yfiance**

**1. Install the library**

In [ ]:
!pip install yfinance

**2. Load stock data**

In [2]:
import yfinance as yf

# Define the stock ticker
ticker = "AAPL"   # Apple Inc.

# Download historical data
data = yf.download(
    ticker,
    start="2020-01-01",
    end="2024-01-01",
    interval="1d"   # daily data
)

/tmp/ipython-input-2113905965.py:7: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(
[*********************100%***********************]  1 of 1 completed

In [4]:
# Explore few rows of the data
data.head()

Price           Close       High        Low       Open     Volume
Ticker           AAPL       AAPL       AAPL       AAPL       AAPL
Date
2020-01-02  72.400528  72.460791  71.156689  71.409793  135480400
2020-01-03  71.696632  72.455950  71.472454  71.629138  146322800
2020-01-06  72.267944  72.306514  70.568518  70.819216  118387200
2020-01-07  71.928055  72.533095  71.708695  72.277578  108872000
2020-01-08  73.085114  73.386431  71.631559  71.631559  132079200

**What you get**

<!DOCTYPE html>
<html>
<head>
<style>
  table { width: 100%; border-collapse: collapse; font-family: sans-serif; }
  th { background-color: #f2f2f2; text-align: left; padding: 12px; border-bottom: 2px solid #ddd; }
  td { padding: 12px; border-bottom: 1px solid #ddd; }
  tr:hover { background-color: #f9f9f9; }
  .code { font-family: monospace; font-weight: bold; color: #d63384; }
</style>
</head>
<body>

<table>
  <thead>
    <tr>
      <th>Column</th>
      <th>Description</th>
      <th>Key Takeaway</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td class="code">Open</td>
      <td>Price at the start of the period.</td>
      <td>Shows initial market sentiment.</td>
    </tr>
    <tr>
      <td class="code">High</td>
      <td>The highest price reached.</td>
      <td>Represents the "ceiling" or resistance.</td>
    </tr>
    <tr>
      <td class="code">Low</td>
      <td>The lowest price reached.</td>
      <td>Represents the "floor" or support.</td>
    </tr>
    <tr>
      <td class="code">Close</td>
      <td>Price at the end of the period.</td>
      <td>Standard benchmark for daily gain/loss.</td>
    </tr>
    <tr>
      <td class="code">Adj Close</td>
      <td>Close price adjusted for splits/dividends.</td>
      <td>**Best for backtesting and ROI.**</td>
    </tr>
    <tr>
      <td class="code">Volume</td>
      <td>Total shares/units traded.</td>
      <td>Measures the strength of a move.</td>
    </tr>
  </tbody>
</table>

</body>
</html>

Indexed by date, which makes it perfect for time-series analysis.

**3. Load multiple stocks**

In [6]:
tickers = ["AAPL", "MSFT", "GOOGL"]

data = yf.download(
    tickers,
    start="2020-01-01",
    end="2024-01-01",
    group_by="ticker"
)

/tmp/ipython-input-1674933461.py:3: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(
[*********************100%***********************]  3 of 3 completed

In [7]:
data.head()

Ticker          GOOGL                                                  AAPL  \
Price            Open       High        Low      Close    Volume       Open
Date
2020-01-02  66.914911  67.920807  66.819630  67.920807  27278000  71.409793
2020-01-03  66.894565  68.172409  66.860816  67.565491  23408000  71.629138
2020-01-06  67.074711  69.391708  67.043453  69.366402  46768000  70.819216
2020-01-07  69.497895  69.648755  69.056232  69.232399  34330000  72.277578
2020-01-08  69.218012  70.063128  69.109336  69.725182  35314000  71.631559

Ticker                                                        MSFT  \
Price            High        Low      Close     Volume        Open
Date
2020-01-02  72.460791  71.156689  72.400528  135480400  150.415292
2020-01-03  72.455950  71.472454  71.696632  146322800  149.979564
2020-01-06  72.306514  70.568518  72.267944  118387200  148.804921
2020-01-07  72.533095  71.708695  71.928055  108872000  150.926859
2020-01-08  73.386431  71.631559  73.085114  132079200  150.557448

Ticker
Price             High         Low       Close    Volume
Date
2020-01-02  152.262561  149.989002  152.158356  22622100
2020-01-03  151.523684  149.733252  150.263748  21116200
2020-01-06  150.718510  148.264942  150.652191  20813700
2020-01-07  151.258412  149.032221  149.278519  21634100
2020-01-08  152.328945  149.629079  151.656342  27746500

**4. Using the Ticker object (more control)**

In [9]:
apple = yf.Ticker("AAPL")

# Historical prices
hist = apple.history(period="5y")

# Corporate actions
dividends = apple.dividends
splits = apple.splits

hist.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2021-02-22 00:00:00-05:00,124.681152,126.346691,122.333827,122.723427,103916400,0.0,0.0
2021-02-23 00:00:00-05:00,120.541670,123.414954,115.311312,122.587059,158273000,0.0,0.0
2021-02-24 00:00:00-05:00,121.690998,122.294870,119.051471,122.090332,111039900,0.0,0.0
2021-02-25 00:00:00-05:00,121.437742,123.171452,117.405402,117.843697,148199500,0.0,0.0
2021-02-26 00:00:00-05:00,119.402113,121.603345,118.048260,118.106705,164560400,0.0,0.0

**Quick tip (important)**

- `Adj Close` is preferred for modeling returns.

- Always check for missing dates and zero volume before training models.

- Market data is **non-stationary**, so preprocessing matters more than the model itself.